version: '3.8'

services:
  emd-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emd-calculator
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    stdin_open: true
    tty: true
